version: '2'


services:

    jenkins-base:
        image: jenkins/jenkins:lts
        restart: unless-stopped
        #environment:
        #    - "NEXUS_CONTEXT=nexus"
        volumes:
            - "${JENKINS_HOME}:/var/jenkins_home"
        restart: unless-stopped # Sometimes it starts too fast, cheap way of retrying...