version: '2'

services:
    jenkins:
        extends:
            file: base.yml
            service: jenkins-base
        restart: unless-stopped
        container_name: jenkins
        hostname: jenkins
        ports:
            - 8080:8080
            - 50000:50000
            