version: '2'
services:

    mysql-master:
        restart: unless-stopped
        container_name: mysql-master
        hostname: mysql-master
        image: mysql
        environment:
          - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
          - "MYSQL_USER=${MYSQL_USER}"
          - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
          - "MYSQL_DATABASE=${MYSQL_DATABASE}"
          - TZ={TZ}
        command:
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
          - --innodb-buffer-pool-size=1G
          - --innodb-flush-log-at-trx-commit=0
          - --innodb-log-file-size=1G
          - --max-allowed-packet=100M
        ports:
          - "33062:3306"
        volumes:
          - "${HOST_MYSQL_DATA_PATH}/data1:/var/lib/mysql"
          - "${HOST_MYSQL_CONFIG_PATH}/conf1.d:/etc/mysql/conf.d"
        networks:
          mysql_net:
            ipv4_address: 172.25.0.2
    mysql-follow:
        restart: unless-stopped
        container_name: mysql-follow
        hostname: mysql-follow
        image: mysql
        environment:
          - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
          - "MYSQL_USER=${MYSQL_USER}"
          - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
          - "MYSQL_DATABASE=${MYSQL_DATABASE}"
          - TZ={TZ}
        command:
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
          - --innodb-buffer-pool-size=1G
          - --innodb-flush-log-at-trx-commit=0
          - --innodb-log-file-size=1G
          - --max-allowed-packet=100M
        ports:
          - "33063:3306"
        volumes:
          - "${HOST_MYSQL_DATA_PATH}/data2:/var/lib/mysql"
          - "${HOST_MYSQL_CONFIG_PATH}/conf2.d:/etc/mysql/conf.d"
        networks:
          mysql_net:
            ipv4_address: 172.25.0.3

networks:
  mysql_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

